// <auto-generated />
using System;
using MBS_SAP.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MBS_SAP.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260625003910_AddP2hTables")]
    partial class AddP2hTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MBS_SAP.Models.ActionPlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlasanOverdue")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alasan_overdue");

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Departemen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen");

                    b.Property<string>("DepartemenPic")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen_pic");

                    b.Property<string>("DepartemenPja")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen_pja");

                    b.Property<string>("DetilLokasi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("detil_lokasi");

                    b.Property<string>("DetilTemuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detil_temuan");

                    b.Property<string>("FotoPerbaikan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_perbaikan");

                    b.Property<string>("FotoTemuan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_temuan");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("ItemSap")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("item_sap");

                    b.Property<string>("KategoriTemuan")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("kategori_temuan");

                    b.Property<string>("Lokasi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("lokasi");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<string>("NikPic")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik_pic");

                    b.Property<string>("NikPja")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik_pja");

                    b.Property<string>("Overdue")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("overdue");

                    b.Property<string>("Perbaikan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("perbaikan");

                    b.Property<int?>("PerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_id");

                    b.Property<string>("Pic")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("pic");

                    b.Property<string>("Pja")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("pja");

                    b.Property<string>("RencanaPerbaikan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("rencana_perbaikan");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal");

                    b.Property<DateTime?>("TanggalPerbaikan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_perbaikan");

                    b.Property<DateTime?>("TanggalRencanaPerbaikan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_rencana_perbaikan");

                    b.Property<TimeSpan>("Waktu")
                        .HasColumnType("time")
                        .HasColumnName("waktu");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_action_plan", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.AppUser", b =>
                {
                    b.Property<string>("Nik")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<string>("Departemen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departemen");

                    b.Property<int?>("IdPerusahaan")
                        .HasColumnType("int")
                        .HasColumnName("id_perusahaan");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2")
                        .HasColumnName("last_login");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("nama");

                    b.Property<string>("Perusahaan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("perusahaan");

                    b.HasKey("Nik");

                    b.ToTable("tbl_t_app_user", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.DepartemenView", b =>
                {
                    b.Property<int>("DepartemenId")
                        .HasColumnType("int")
                        .HasColumnName("departemen_id");

                    b.Property<int?>("IdPerusahaan")
                        .HasColumnType("int")
                        .HasColumnName("id_perusahaan");

                    b.Property<string>("KodeDepartemen")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("kode_departemen");

                    b.Property<string>("NamaDepartemen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nama_departemen");

                    b.Property<string>("StatusAktif")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status_aktif");

                    b.HasKey("DepartemenId");

                    b.ToTable((string)null);

                    b.ToView("vw_departemen", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.HazardReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Departemen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen");

                    b.Property<string>("DepartemenPja")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen_pja");

                    b.Property<string>("DetilLokasi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("detil_lokasi");

                    b.Property<string>("FotoTemuan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_temuan");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JenisBahaya")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("jenis_bahaya");

                    b.Property<string>("JenisKetidaksesuaian")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("jenis_ketidaksesuaian");

                    b.Property<string>("KategoriBahaya")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("kategori_bahaya");

                    b.Property<string>("Lokasi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("lokasi");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<string>("NikPja")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik_pja");

                    b.Property<string>("Perbaikan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("perbaikan");

                    b.Property<int?>("PerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_id");

                    b.Property<string>("Pja")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("pja");

                    b.Property<string>("StatusTemuan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status_temuan");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal");

                    b.Property<string>("Temuan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("temuan");

                    b.Property<string>("TindakanPerbaikan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tindakan_perbaikan");

                    b.Property<string>("TingkatResiko")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tingkat_resiko");

                    b.Property<TimeSpan>("Waktu")
                        .HasColumnType("time")
                        .HasColumnName("waktu");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_hazard_report", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.Inspection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("area");

                    b.Property<string>("Catatan")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("catatan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Departemen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen");

                    b.Property<string>("DepartemenPja")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen_pja");

                    b.Property<string>("DetilLokasi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("detil_lokasi");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JenisInspeksi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("jenis_inspeksi");

                    b.Property<string>("LampiranJson")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("lampiran_json");

                    b.Property<string>("Lokasi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("lokasi");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<string>("NikPja")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik_pja");

                    b.Property<int?>("PerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_id");

                    b.Property<string>("Pja")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("pja");

                    b.Property<int>("Q1_1")
                        .HasColumnType("int")
                        .HasColumnName("q1_1");

                    b.Property<int>("Q1_2")
                        .HasColumnType("int")
                        .HasColumnName("q1_2");

                    b.Property<int>("Q1_3")
                        .HasColumnType("int")
                        .HasColumnName("q1_3");

                    b.Property<int>("Q2_1")
                        .HasColumnType("int")
                        .HasColumnName("q2_1");

                    b.Property<int>("Q2_2")
                        .HasColumnType("int")
                        .HasColumnName("q2_2");

                    b.Property<int>("Q2_3")
                        .HasColumnType("int")
                        .HasColumnName("q2_3");

                    b.Property<int>("Q3_1")
                        .HasColumnType("int")
                        .HasColumnName("q3_1");

                    b.Property<int>("Q3_2")
                        .HasColumnType("int")
                        .HasColumnName("q3_2");

                    b.Property<int>("Q3_3")
                        .HasColumnType("int")
                        .HasColumnName("q3_3");

                    b.Property<int>("Q4_1")
                        .HasColumnType("int")
                        .HasColumnName("q4_1");

                    b.Property<int>("Q4_2")
                        .HasColumnType("int")
                        .HasColumnName("q4_2");

                    b.Property<int>("Q4_3")
                        .HasColumnType("int")
                        .HasColumnName("q4_3");

                    b.Property<int>("Q5_1")
                        .HasColumnType("int")
                        .HasColumnName("q5_1");

                    b.Property<int>("Q5_2")
                        .HasColumnType("int")
                        .HasColumnName("q5_2");

                    b.Property<int>("Q5_3")
                        .HasColumnType("int")
                        .HasColumnName("q5_3");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal");

                    b.Property<TimeSpan>("Waktu")
                        .HasColumnType("time")
                        .HasColumnName("waktu");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_inspection", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.JabatanView", b =>
                {
                    b.Property<int>("JabatanId")
                        .HasColumnType("int")
                        .HasColumnName("jabatan_id");

                    b.Property<int?>("IdPerusahaan")
                        .HasColumnType("int")
                        .HasColumnName("id_perusahaan");

                    b.Property<int?>("IdSeksi")
                        .HasColumnType("int")
                        .HasColumnName("id_seksi");

                    b.Property<string>("KodeJabatan")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("kode_jabatan");

                    b.Property<string>("NamaJabatan")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nama_jabatan");

                    b.Property<string>("StatusAktif")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("status_aktif");

                    b.HasKey("JabatanId");

                    b.ToTable((string)null);

                    b.ToView("vw_jabatan", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.KaryawanView", b =>
                {
                    b.Property<int>("IdKaryawan")
                        .HasColumnType("int")
                        .HasColumnName("id_karyawan");

                    b.Property<int?>("IdDepartemen")
                        .HasColumnType("int")
                        .HasColumnName("id_departemen");

                    b.Property<int?>("IdJabatan")
                        .HasColumnType("int")
                        .HasColumnName("id_jabatan");

                    b.Property<int>("IdPersonal")
                        .HasColumnType("int")
                        .HasColumnName("id_personal");

                    b.Property<int>("IdPerusahaan")
                        .HasColumnType("int")
                        .HasColumnName("id_perusahaan");

                    b.Property<int?>("IdSeksi")
                        .HasColumnType("int")
                        .HasColumnName("id_seksi");

                    b.Property<string>("NoNik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("no_nik");

                    b.Property<int?>("PerusahaanNodeId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_node_id");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("bit")
                        .HasColumnName("status_aktif");

                    b.Property<DateTime?>("TanggalMasuk")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_masuk");

                    b.HasKey("IdKaryawan");

                    b.ToTable((string)null);

                    b.ToView("vw_karyawan", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.MasterArea", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedByName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("created_by_name");

                    b.Property<string>("CreatedByNik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("created_by_nik");

                    b.Property<string>("NamaArea")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama_area");

                    b.Property<int>("PerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_id");

                    b.HasKey("Id");

                    b.ToTable("tbl_m_area_utama", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.Notification", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit")
                        .HasColumnName("is_read");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("message");

                    b.Property<string>("RecipientNik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("recipient_nik");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_notifications");
                });

            modelBuilder.Entity("MBS_SAP.Models.Observation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Departemen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departemen");

                    b.Property<string>("DepartemenYangDiamati")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("departemen_yang_diamati");

                    b.Property<string>("DetilLokasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detil_lokasi");

                    b.Property<string>("DokumenPendukung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("dokumen_pendukung");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_url");

                    b.Property<string>("HasilObservasi")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hasil_observasi");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("KegiatanYangDiamati")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kegiatan_yang_diamati");

                    b.Property<string>("Keterangan")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Lokasi")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("lokasi");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<string>("PerihalYangDiamati")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("perihal_yang_diamati");

                    b.Property<string>("ResikoKritis")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("resiko_kritis");

                    b.Property<string>("TingkatResiko")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("tingkat_resiko");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_observation", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.P2hReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FotoSpeedometer")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_speedometer");

                    b.Property<string>("GolA_Json")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gol_a_json");

                    b.Property<string>("GolB_Json")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gol_b_json");

                    b.Property<string>("GolC_Json")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gol_c_json");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JenisKendaraan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("jenis_kendaraan");

                    b.Property<double>("Kilometer")
                        .HasColumnType("float")
                        .HasColumnName("kilometer");

                    b.Property<string>("Merek")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("merek");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<string>("NoLambung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("no_lambung");

                    b.Property<string>("SimperKimper")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("simper_kimper");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal");

                    b.Property<TimeSpan>("Waktu")
                        .HasColumnType("time")
                        .HasColumnName("waktu");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_p2h_report", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.P2hVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("JenisKendaraan")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("jenis_kendaraan");

                    b.Property<string>("Merek")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("merek");

                    b.Property<string>("NoLambung")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("no_lambung");

                    b.HasKey("Id");

                    b.ToTable("tbl_m_p2h_vehicle", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.P5m", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("area");

                    b.Property<string>("Catatan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("catatan");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Departemen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen");

                    b.Property<string>("DetilLokasi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("detil_lokasi");

                    b.Property<string>("FotoKegiatan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_kegiatan");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Jawaban")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("jawaban");

                    b.Property<string>("Judul")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("judul");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keterangan");

                    b.Property<string>("ListPertanyaan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("list_pertanyaan");

                    b.Property<string>("Lokasi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("lokasi");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<int?>("PerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_id");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal");

                    b.Property<string>("Topik")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("topik");

                    b.Property<TimeSpan>("Waktu")
                        .HasColumnType("time")
                        .HasColumnName("waktu");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_p5m", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.PasswordOverride", b =>
                {
                    b.Property<string>("Nrp")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nrp");

                    b.Property<DateTime>("DiubahPada")
                        .HasColumnType("datetime2")
                        .HasColumnName("diubah_pada");

                    b.Property<bool>("HasAgreedToTerms")
                        .HasColumnType("bit")
                        .HasColumnName("has_agreed_to_terms");

                    b.Property<string>("KataSandi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("kata_sandi");

                    b.Property<string>("ProfilePicture")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("profile_picture");

                    b.HasKey("Nrp");

                    b.ToTable("tbl_m_pengguna_sandi", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.PenggunaView", b =>
                {
                    b.Property<int>("PenggunaId")
                        .HasColumnType("int")
                        .HasColumnName("pengguna_id");

                    b.Property<int?>("DepartemenId")
                        .HasColumnType("int")
                        .HasColumnName("departemen_id");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email");

                    b.Property<bool>("IsAktif")
                        .HasColumnType("bit")
                        .HasColumnName("is_aktif");

                    b.Property<int?>("JabatanId")
                        .HasColumnType("int")
                        .HasColumnName("jabatan_id");

                    b.Property<string>("KataSandi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("kata_sandi");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama_lengkap");

                    b.Property<int>("PeranId")
                        .HasColumnType("int")
                        .HasColumnName("peran_id");

                    b.Property<int>("PerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_id");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("username");

                    b.HasKey("PenggunaId");

                    b.ToTable((string)null);

                    b.ToView("vw_pengguna", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.PersonalView", b =>
                {
                    b.Property<int>("IdPersonal")
                        .HasColumnType("int")
                        .HasColumnName("id_personal");

                    b.Property<string>("Alamat")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("alamat");

                    b.Property<string>("EmailPribadi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("email_pribadi");

                    b.Property<string>("Hp1")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("hp_1");

                    b.Property<string>("JenisKelamin")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("jenis_kelamin");

                    b.Property<string>("NamaLengkap")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)")
                        .HasColumnName("nama_lengkap");

                    b.Property<string>("NoKtp")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("no_ktp");

                    b.Property<DateTime?>("TanggalLahir")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_lahir");

                    b.HasKey("IdPersonal");

                    b.ToTable((string)null);

                    b.ToView("vw_personal", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.PerusahaanView", b =>
                {
                    b.Property<int>("PerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_id");

                    b.Property<string>("KodePerusahaan")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("kode_perusahaan");

                    b.Property<string>("NamaPerusahaan")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("nama_perusahaan");

                    b.Property<int?>("PerusahaanIndukId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_induk_id");

                    b.Property<bool>("StatusAktif")
                        .HasColumnType("bit")
                        .HasColumnName("status_aktif");

                    b.Property<int?>("TipePerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("tipe_perusahaan_id");

                    b.HasKey("PerusahaanId");

                    b.ToTable((string)null);

                    b.ToView("vw_perusahaan", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.Quiz", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<string>("Platform")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("platform");

                    b.Property<int>("Score")
                        .HasColumnType("int")
                        .HasColumnName("score");

                    b.HasKey("Id");

                    b.ToTable("table_m_quis", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.QuizAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CorrectAnswerText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correct_answer_text");

                    b.Property<string>("CorrectKey")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("correct_key");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<int>("PointsEarned")
                        .HasColumnType("int")
                        .HasColumnName("points_earned");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("question");

                    b.Property<int>("QuizId")
                        .HasColumnType("int")
                        .HasColumnName("quiz_id");

                    b.Property<string>("SelectedAnswer")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("selected_answer");

                    b.Property<string>("SelectedAnswerText")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("selected_answer_text");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("table_m_quis_detail", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.RunningText", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsAktif")
                        .HasColumnType("bit")
                        .HasColumnName("is_aktif");

                    b.Property<string>("Pesan")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pesan");

                    b.HasKey("Id");

                    b.ToTable("tbl_m_running_text", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.SafetyTalk", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Area")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("area");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Departemen")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("departemen");

                    b.Property<string>("DetilLokasi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("detil_lokasi");

                    b.Property<string>("FotoDiri")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_diri");

                    b.Property<string>("FotoKegiatan")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("foto_kegiatan");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_deleted");

                    b.Property<string>("Judul")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)")
                        .HasColumnName("judul");

                    b.Property<string>("Keterangan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("keterangan");

                    b.Property<string>("Lokasi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("lokasi");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama");

                    b.Property<string>("Nik")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.Property<int?>("PerusahaanId")
                        .HasColumnType("int")
                        .HasColumnName("perusahaan_id");

                    b.Property<DateTime>("Tanggal")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal");

                    b.Property<TimeSpan>("Waktu")
                        .HasColumnType("time")
                        .HasColumnName("waktu");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_safety_talk", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.TimelineComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("comment_text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("item_type");

                    b.Property<string>("NamaPengguna")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)")
                        .HasColumnName("nama_pengguna");

                    b.Property<string>("Nik")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_comments", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.TimelineLike", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<int>("ItemId")
                        .HasColumnType("int")
                        .HasColumnName("item_id");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("item_type");

                    b.Property<string>("Nik")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("nik");

                    b.HasKey("Id");

                    b.ToTable("tbl_t_likes", (string)null);
                });

            modelBuilder.Entity("MBS_SAP.Models.QuizAnswer", b =>
                {
                    b.HasOne("MBS_SAP.Models.Quiz", "Quiz")
                        .WithMany("Answers")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("MBS_SAP.Models.Quiz", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
